components:
  securitySchemes:
    Cognito:
      description: Cognito JWT (use "Bearer XYZ" as value)
      in: header
      name: Authorization
      type: apiKey
externalDocs:
  description: ""
  url: ""
info:
  title: API go template
  version: ""
openapi: 3.1.0
paths:
  /api/go-api-template/sample:
    get:
      description: Returns a sample message
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
          description: OK
      security:
      - Cognito: []
      summary: Sample handler
      tags:
      - Sample
