// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockService is an autogenerated mock type for the ServiceItf type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// SampleMethod provides a mock function with no fields
func (_m *MockService) SampleMethod() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SampleMethod")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockService_SampleMethod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SampleMethod'
type MockService_SampleMethod_Call struct {
	*mock.Call
}

// SampleMethod is a helper method to define mock.On call
func (_e *MockService_Expecter) SampleMethod() *MockService_SampleMethod_Call {
	return &MockService_SampleMethod_Call{Call: _e.mock.On("SampleMethod")}
}

func (_c *MockService_SampleMethod_Call) Run(run func()) *MockService_SampleMethod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_SampleMethod_Call) Return(_a0 string) *MockService_SampleMethod_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_SampleMethod_Call) RunAndReturn(run func() string) *MockService_SampleMethod_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
