name: Build and Test
run-name: Build and Test ${{ github.head_ref }}

description: Build and Test the api code on pull requests to the main branch

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: 

concurrency: 
  group: 'build-and-test ${{ github.head_ref }}'
  cancel-in-progress: true

permissions: 
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: ./go.mod
          cache: true
          cache-dependency-path: ./go.sum

      - name: Install dependencies
        run: go mod vendor
        background: true

      - name: Install tools
        run: |-
          go install github.com/vektra/mockery/v2@latest
          go install github.com/swaggo/swag/v2/cmd/swag@latest
          go install gotest.tools/gotestsum@latest
        background: true

      - name: Install task
        run: |-
          curl -1sLf 'https://dl.cloudsmith.io/public/task/task/setup.deb.sh' | sudo -E bash 
          sudo apt install task -y
        background: true

      - name: Wait for install tasks
        wait-all: 

      - name: Generate
        run: task generate

      - name: Tests
        id: Tests
        run: task test
        background: true

      - name: Build
        id: Build
        run: task build
        background: true

      - name: Wait for build and test
        wait: [Tests, Build]